name: Python

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: sudo apt-get install gettext python3 libgpgme-dev
    - name: Install python dependencies
      run: sudo pip3 install .
    - name: Build torbrowser-launcher
      run: python3 setup.py build
    - name: Install torbrowser-launcher
      run: sudo python3 setup.py install
